import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Banner from '@/components/banner/banner'
import CardStoreItem from '@/components/card-Store-Item/cardStoreItem'
import cls from "classnames"
import coffeStoresData from '/data/coffee-stores.json'

export async function getStaticProps(context) {
  /* const data = fetch(coffeStores)  if we have a server*/
  return {
    props: {
      coffeStores:coffeStoresData,
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  const viewSotresNearBy = () => {
    console.log('banner clicked');
  }
  return (
    <div>
      <div className={cls("container")}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>

          {/* Banner section */}
          <Banner buttonText= 'View Stores nearby' handleOnClick= {viewSotresNearBy}/>
          {/* Stores section */}
          {props.coffeStores.length > 0 && (
            <div>
              <h2 className={styles.town}>Algies stores</h2>
              <div className={styles.cardStoreItems}>
                {props.coffeStores.map((coffeStore) => { 
                  return (
                  <CardStoreItem
                    key={coffeStore.id}
                    name = {coffeStore.name} 
                    imgUrl = {coffeStore.imgUrl} 
                    href = {`./coffee-stores/${coffeStore.name}`} 
                  />
                  );
                })}
              </div>
            </div>)}
          
        </main>
      </div>
    </div>
  )
}