import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Banner from '@/components/banner/banner'
import CardStoreItem from '@/components/card-Store-Item/cardStoreItem'
import cls from "classnames"
import { fetchedCoffeStores } from '@/lib/coffeeStores'

export async function getStaticProps(context) {

  const coffeStores = await fetchedCoffeStores ();
  console.log(coffeStores);
  return {
    props: {
      coffeStores,
    }, // will be passed to the page component as props
  }
}
export default function Home({coffeStores}) {
  const viewSotresNearBy = () => {
    console.log('banner clicked');
  }
  return (
    <div>
      <div className={cls("container")}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {/* Banner section */}
          <Banner buttonText= 'View Stores nearby' handleOnClick= {viewSotresNearBy}/>
          {/* Stores section */}
          {coffeStores.length > 0 && (
            <div>
              <h2 className={styles.town}>Algies stores</h2>
              <div className={styles.cardStoreItems}>
                {coffeStores.map((coffeStore) => { 
                  return (
                  <CardStoreItem
                    key={coffeStore.number}
                    name = {coffeStore.placeLabel} 
                    imgUrl = {"https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"} 
                    href = {`./coffee-stores/${coffeStore.number}`} 
                  />
                  );
                })}
              </div>
            </div>)} 
        </main>
      </div>
    </div>
  )
}