import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import Banner from '@/components/banner/banner'
import CardStoreItem from '@/components/card-Store-Item/cardStoreItem'
import cls from "classnames"
import { fetchedCoffeStores } from '@/lib/coffeeStores'
import useTrackLocation from '@/hooks/use-track-location'

export async function getStaticProps(context) {

  const coffeStores = await fetchedCoffeStores ();
  return {
    props: {
      coffeStores,
    }, // will be passed to the page component as props
  }
}

export default function Home({coffeStores}) {

  const {handleTrackLocation, latLong, locationErrorMsg,isFindLocation} = useTrackLocation();
  const viewSotresNearBy = () => {
    console.log({latLong,locationErrorMsg});
    handleTrackLocation();
  }
  return (
    <div>
      <div className={cls("container")}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          {/* Banner section */}
          <Banner buttonText= {isFindLocation ? "Locating...":'View Stores nearby'} handleOnClick= {viewSotresNearBy}/>
          {/* Stores section */}
          {coffeStores.length > 0 && (
            <div>
              <h2 className={styles.town}>Algies stores</h2>
              <div className={styles.cardStoreItems}>
                {coffeStores.map((coffeStore) => { 
                  return (
                  <CardStoreItem
                    key={coffeStore.id}
                    name = {coffeStore.name} 
                    imgUrl = {coffeStore.imgUrl} 
                    href = {`./coffee-stores/${coffeStore.id}`} 
                  />
                  );
                })}
              </div>
            </div>)} 
        </main>
      </div>
    </div>
  )
}